### ISSUE TITLE
Highlighting unreadable

### ISSUE THREAD

**Issue by macterra** [shodty/shodty.github.io#1]
Now seeing white text on light yellow background which is very hard to read highlights (text between ^^) 
https://shodty.github.io/Dark_Age.css

**Comment by shodty** [comment]
Hey @macterra thanks for the headsup! This should be fixed now, seems Roam had changed the highlighter class on their end. 
Colors can be adjusted using the --highlighter & --highte-text-color variables I established under root! Let me know if you have any further issues :)

**Comment by macterra** [comment]
All good now, and thanks so much for the Dark_Age theme!
